env:
  #todo - add k3d too
  local_kube: minikube
  
  #todo - add podman too
  engine: docker 
  ## namespace for all that we deploy here
  namespace: localk8s-dev

deploys:
  # deployment 1
  - name: my_deployment
    replicas: 3
    port: 80
    
    engine:
    #image 1
      - image_name: image_url
        image_tag: v1
        # dockerfile path 
        file_path: path/to/docker/file
        port: 80

       image 2
       - image_name: image2
         image_tag: v1
         file_path:
         port:
  
  # deployment 2
  - name: second_deployment
    replicas: 3
    port: 80
    
    engine:
    #image 1
      - image_name: another_image
        image_tag: v1
        # dockerfile path 
        file_path: path/to/another/docker/file
        port: 80
