---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-site
  namespace: hugo-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hugo-site
  template:
    metadata:
      labels:
        app: hugo-site
    spec:
      containers:
      - name: hugo-site
        image: mydockerhubusername/hugo-site:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hugo-site
  namespace: hugo-site
spec:
  selector:
    app: hugo-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
