---
- name: create cluster
  hosts: localhost
  gather_facts: False

  tasks:
    - include_vars: ../config.yml

    - name: check the status of {{ env.local_kube }}.
      command: "{{ env.local_kube }} status"
      register: kube_status
      changed_when: false
      ignore_errors: true

    - name: start {{ env.local_kube }} if it's not running.
      command: "{{ env.local_kube }} start"
      when: "not kube_status.stdout or 'Running' not in kube_status.stdout"

    - name: unpause {{ env.local_kube }} if it's paused.
      command: "{{ env.local_kube }} unpause"
      when: "'Paused' in kube_status.stdout"
