---
- name: deploy app with 
  hosts: localhost
  gather_facts: False

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    eng_containers: []
  
  pre_tasks:
    - include_vars: ../config.yml

    - name: check the status of {{ env.local_kube }}.
      command: "{{ env.local_kube }} status"
      register: kube_status
      changed_when: false
      ignore_errors: true
    
    - name: make sure to start {{ env.local_kube }}
      fail:
        msg: "Please run create_cluster first"
      when: "not kube_status.stdout or 'Running' not in kube_status.stdout or 'Paused' in kube_status.stdout"

  tasks:
    - name: create namespace
      community.kubernetes.k8s:
        name: "{{ env.namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: create deployments
      vars:
        eng_images: "{{ deploy.engine | flatten }}"
        deploy_port: "{{ deploy.port }}"
        deploy_name: "{{ deploy.name }}"
        deploy_replicas: "{{ deploy.replicas }}"

      include_tasks: include/deploy_tasks.yml

      loop: "{{ deploys | flatten }}"
      loop_control:
        loop_var: deploy
